spring:
  application:
    name: Login
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 7OHbCOYGnO03OtHtM4oy5IjBgMBoJsmO
            client-secret: 3nbXjGutr5e0obLFUggGHaua1x7Okt1Az1i1eCjPwxWiIUQqwnhuz3I8mmGQKVdw
            scope: openid+profile+email
        provider:
          auth0:
            issuer-uri: https://dev-sim47gxurdmw2ilx.us.auth0.com/

logging:
  level:
    org.springframework.security: DEBUG